edad = 70
if edad > 65: #Siempre que la condicion junto al If se evalue en verdadero o falso, se cumplira el codigo de abajo
    print("Puede ver la pelicula con super descuento")
elif edad > 54: # Sino se cumple la primera condicion, en su lugar se cumplira esta
    print("Puede ver la pelicula con descuento") 
elif edad > 17:
    print("Puedes ver la pelicula ")
# else: # sino se cumple ninguna de las dos primeras condiciones se ejecutara else y su codigo
#    print("No puedes entrar")
#    print("Ve a otro lado")

print("Listo") 